export const _id = (index: number) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index}`;

export const _times = (index: number) =>
  // 'MM/DD/YYYY'
  [
    '10/01/2025',
    '04/09/2025',
    '05/12/2025',
    '12/23/2024',
    '04/26/2025',
    '02/29/2024',
    '05/14/2024',
    '01/13/2024',
    '06/22/2024',
    '10/05/2023',
    '07/11/2024',
    '05/22/2024',
    '03/29/2024',
    '08/29/2023',
    '11/19/2023',
    '10/24/2023',
    '12/02/2023',
    '02/13/2024',
    '09/19/2023',
    '04/17/2024',
    '12/18/2023',
    '06/27/2024',
    '10/19/2023',
    '08/09/2024',
  ][index];

export const _fullName = (index: number) =>
  [
    'Netflix',
    'Amazon Prime Video',
    'Disney+ Hotstar',
    'Spotify Premium',
    'Youtube Premium',
    'Apple Music',
    'Microsoft 365 (Office 365)',
    'Google One',
    'Adobe Creative Cloud',
    'Notion Plus',
    'Canva Pro',
    'Google Workspace',
    'Amazon Prime (Shopping)',
    'Flipkart Plus',
    'Zomato Gold',
    'BigBasket Membership',
    'Paytm Wallet Plus',
    'Dropbox',
    '1Password',
    'Cult.fit',
    'Headspace',
    'MyFitnessPal Premium',
    'Xbox Game Pass',
    'Google Play Pass',
  ][index];

export const _price = (index: number) =>
  [
    35.17, 57.22, 64.78, 50.79, 9.57, 61.46, 96.73, 63.04, 33.18, 36.3, 54.42, 20.52, 62.82, 19.96,
    25.93, 70.39, 23.11, 67.23, 14.31, 31.5, 26.72, 44.8, 37.87, 75.53,
  ][index];

export const _company = (index: number) =>
  [
    'Netflix Inc.',
    'Amazon',
    'Disney / Hotstar',
    'Spotify AB',
    'Google ',
    'Apple Inc.',
    'Microsoft',
    'Google',
    'Adobe Inc.',
    'Notion Labs',
    'Canva Pty Ltd',
    'Google',
    'Amazon',
    'Flipkart',
    'Zomato',
    'BigBasket',
    'Paytm',
    'Dropbox Inc.',
    'AgileBits',
    'Cult.fit',
    'Headspace',
    'MyFitnessPal Inc.',
    'Microsoft',
    'Google',
  ][index];

export const _boolean = (index: number) =>
  [
    true,
    false,
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
  ][index];

export const _postTitles = (index: number) =>
  [
    'Monthly Spending Report: October Summary',
    'New Subscription Detected: Spotify Premium',
    'Smart Tip: Save ₹500 on Your Next Utility Bill',
    'Budget Goal Reached: Travel Fund',
    'Insight: Subscriptions Cost You ₹2,850 This Month',
    'Six Socks Studio',
    'vincenzo de cotiis’ crossing over showcases a research on contamination',
    'Simple, Great Looking Animations in Your Project | Video Tutorial',
    '40 Free Serif Fonts for Digital Designers',
    'Examining the Evolution of the Typical Web Design Client',
    'Katie Griffin loves making that homey art',
    'The American Dream retold through mid-century railroad graphics',
    'Illustration System Design',
    'CarZio-Delivery Driver App SignIn/SignUp',
    'How to create a client-serverless Jamstack app using Netlify, Gatsby and Fauna',
    'Tylko Organise effortlessly -3D & Motion Design',
    'RAYO ?? A expanded visual arts festival identity',
    'Anthony Burrill and Wired mag’s Andrew Diprose discuss how they made January’s Change Everything cover',
    'Inside the Mind of Samuel Day',
    'Portfolio Review: Is This Portfolio Too Creative?',
    'Akkers van Margraten',
    'Gradient Ticket icon',
    'Here’s a Dyson motorcycle concept that doesn’t ‘suck’!',
    'How to Animate a SVG with border-image',
  ][index];

export const _description = (index: number) =>
  [
    'Your total spending increased by 8% this month. Entertainment and food subscriptions were your top categories.',
    'A new recurring charge of ₹249/month was detected for Spotify Premium and added to your Subscriptions tab.',
    'You’re close to exceeding your monthly budget limit. Set an alert to get notified for high spending activity.',
    'You saved ₹5,000 this month great progress toward your savings goal!',
    'SmartSpend detected 5 active subscriptions. Review and cancel the ones you no longer use to save money.',
    'Your total savings grew by 12% since last quarter — consistent saving habits are paying off.',
    'Last week’s highest spending was on dining. Consider setting a weekly dining cap to stay on track.',
    'You received a cashback of ₹200 on your latest bill payment — keep it up!',
    'You’ve been spending more on OTT subscriptions recently. Review your streaming plans for better deals.',
    'SmartSpend insights show that your average monthly expense is ₹22,000 — 5% lower than last month.',
    'Your credit card bill is due in 3 days. Avoid late fees by paying it early.',
    'You earned ₹3,500 in rewards and cashback this month through your linked accounts.',
    'Electricity expenses went up by 9%. Consider switching to an energy-saving plan.',
    'Your yearly subscription summary is ready. Review and optimize recurring expenses for 2025.',
    'SmartSpend detected duplicate subscriptions on two platforms — merge or cancel one to reduce costs.',
    'Entertainment subscriptions form 28% of your total expenses — it’s time to review your priorities.',
    'Your grocery expenses decreased by 7% compared to last month — good budgeting!',
    'You’ve maintained a positive savings-to-expense ratio for three consecutive months.',
    'A new auto-renewal charge was detected — review before the next billing cycle.',
    'Your monthly financial report is ready. Check your insights dashboard for detailed analytics.',
    'You’ve hit your savings target 3 days early. Let’s set a new goal for next month.',
    'SmartSpend recommends setting up automatic transfers to your savings account for consistency.',
    'You cancelled 2 unused subscriptions this week, saving ₹1,400 monthly.',
    'Your financial health score improved by 10 points this month — keep monitoring your insights regularly.',
  ][index];

export const _taskNames = (index: number) =>
  [
    `Review Monthly Spending Report`,
    `Pay Credit Card Bill`,
    `Update Monthly Budget Plan`,
    `Track Upcoming Subscription Renewals`,
    `Analyze Weekly Expense Trends`,
    `Reconcile Bank Transactions`,
    `Set Savings Goal for the Month`,
    `Evaluate Investment Portfolio`,
    `Categorize Recent Transactions`,
    `Generate Expense Summary`,
    `Plan Next Month’s Budget`,
    `Review Loan Payment Schedule`,
    `Check Credit Score Updates`,
    `Set Up Emergency Fund Target`,
    `Update Income Records`,
    `Verify Automatic Payments`,
    `Monitor Utility Bill Changes`,
    `Analyze Recurring Expenses`,
    `Schedule Tax Payment Reminder`,
    `Review Financial Insights`,
    `Cancel Unused Subscriptions`,
    `Compare Monthly Cash Flow`,
    `Plan Budget Adjustments`,
    `Track Daily Spending Activity`,
  ][index];

export const _productNames = (index: number) =>
  [
    'Nike Air Force 1 NDESTRUKT',
    'Nike Space Hippie 04',
    'Nike Air Zoom Pegasus 37 A.I.R. Chaz Bear',
    'Nike Blazer Low 77 Vintage',
    'Nike ZoomX SuperRep Surge',
    'Zoom Freak 2',
    'Nike Air Max Zephyr',
    'Jordan Delta',
    'Air Jordan XXXV PF',
    'Nike Waffle Racer Crater',
    'Kyrie 7 EP Sisterhood',
    'Nike Air Zoom BB NXT',
    'Nike Air Force 1 07 LX',
    'Nike Air Force 1 Shadow SE',
    'Nike Air Zoom Tempo NEXT%',
    'Nike DBreak-Type',
    'Nike Air Max Up',
    'Nike Air Max 270 React ENG',
    'NikeCourt Royale',
    'Nike Air Zoom Pegasus 37 Premium',
    'Nike Air Zoom SuperRep',
    'NikeCourt Royale',
    'Nike React Art3mis',
    'Nike React Infinity Run Flyknit A.I.R. Chaz Bear',
  ][index];
